version: '3.8'

services:
  fuseki:
    image: secoresearch/fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - fuseki_data:/fuseki

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
      - ./ontology/data/image:/code/images
    environment:
      - FUSEKI_URL=http://fuseki:3030/safi/sparql
      - FUSEKI_UPDATE_URL=http://fuseki:3030/safi/update
    env_file:
      - ./backend/.env
    depends_on:
      - fuseki

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  fuseki_data:
