PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX safi: <http://example.org/safionto/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT ?monument ?name ?description WHERE {
    ?monument rdf:type safi:HeritageMonument .
    OPTIONAL { ?monument rdfs:label ?name }
    OPTIONAL { ?monument safi:hasDescription ?description }
}
